Switch component
soramitsu/soramitsu-js-ui-library pull request #355
Opened 2022-01-17 15:16 UTC by RustemYuzlibaev

2022-01-17 15:39 UTC, 0x009922 requested changes
Everything is great. But I miss the main feature of the component - control it via `v-model` )

2022-01-18 07:18 UTC, RustemYuzlibaev commented
> Everything is great. But I miss the main feature of the component - control it via `v-model` )

Decided to implement with Vue3 approach using **defineEmits** as in Alert component
If I get correctly we can control this way as well as via v-model?

2022-01-18 08:20 UTC, 0x009922 commented
@RustemYuzlibaev, I think the best way to implement it is to use `modelValue` as prop and `update:modelValue` as event, so it will be possible to use switch component like this:

```html
<SSwitch v-model="checked" />
```

2022-01-18 08:22 UTC, 0x009922 requested changes
- Use `modelValue` & `update:modelValue` (also look at `useVModel()` from [VueUse](https://vueuse.org/core/usevmodel/))
- Add Cypress test case with modeling check

2022-01-31 12:52 UTC, 0x009922 commented on packages/ui/src/components/Switch/SSwitch.vue
> +  </div>
According to BEM, isn't it correct to name sub-elements like `s-switch__button` & `s-switch__label`?

2022-01-31 12:53 UTC, 0x009922 commented on packages/ui/cypress/component/SSwitch.spec.cy.ts
> +  mount(SSwitch, { props: { id: 'id', checked: false } })
Component doesn't have a prop with name `checked`.

2022-01-31 12:54 UTC, 0x009922 requested changes
Can you please resolve comments and add Cypress test for ID binding (ensure that id for label & input are the same)?

2022-02-01 07:20 UTC, 0x009922 commented on packages/ui/src/components/Alert/SAlert.vue
> +      <button data-testid="close-btn" @click="onClickClose">
Looks like formatting is broken :<

2022-02-01 07:20 UTC, 0x009922 commented on packages/ui/src/components/Alert/SAlert.vue
> +  <div class="s-alert" :data-status="status" :data-inline="inline">
Here formatting is broken too

2022-02-01 07:21 UTC, 0x009922 commented on packages/ui/src/components/Switch/SSwitch.vue
> +  </div>
And here I see some formatting problems

2022-02-01 07:21 UTC, 0x009922 requested changes
Fix formatting please

2022-02-01 07:23 UTC, 0x009922 approved these changes

2022-02-01 07:57 UTC, stefashkaa approved these changes

2022-02-01 07:58 UTC, merged