WDS-74 - ProgressBar component
soramitsu/soramitsu-js-ui-library pull request #357
Opened 2022-01-21 06:36 UTC by timofeytrepalin

2022-01-21 09:54 UTC, 0x009922 commented on packages/ui/src/components/ProgressBar/SProgressBar.vue
> +    return props.percent < 0
Not critical, but I would rewrite it like this:

```js
`${Math.min(Math.max(props.percent, 0), 100)}%`
```

or

```js
const val = props.percent;
`${val < 0 ? 0 : val > 100 ? 100 : val}%`
```

2022-01-21 09:55 UTC, 0x009922 approved these changes

2022-02-02 13:23 UTC, 0x009922 requested changes

2022-02-02 13:23 UTC, 0x009922 commented on packages/ui/src/components/ProgressBar/SProgressBar.vue
> +    background: linear-gradient(90deg, var(--s-color-theme-accent) $active-bar-width, transparent 0%);
Please use correct theme binding

2022-02-07 05:54 UTC, 0x009922 commented
Also please add a minor changeset

2022-02-09 06:05 UTC, 0x009922 commented on .changeset/config.json
> -  "baseBranch": "master",
Don't include this change, please

2022-02-09 09:04 UTC, 0x009922 approved these changes

2022-04-11 17:06 UTC, stefashkaa approved these changes

2022-04-19 23:52 UTC, merged