Feature/wds 57 menu component
soramitsu/soramitsu-js-ui-library pull request #411
Opened 2022-05-16 14:30 UTC by Ctepan

Added title removing form svg
Added SCollapse component
Added SMenu component

2022-05-18 12:58 UTC, 0x009922 commented on packages/ui/cypress/component/SMenu.spec.cy.ts
> +  const initiallySelectedItem = '1'
Usually variables for const values like these are written in `SCREAMING_CASE`.

2022-05-18 13:31 UTC, 0x009922 requested changes
General comment about naming. I am confused by `SMenu` and `SSubmenu` components. Based on my experience with other UI libraries, usually `Menu` is about a context menu, a popup menu, or something like `<select>`. In our case, we have a navigation menu, which is quite different.

I think `SNavMenu` and `SNavSubMenu` would be more appropriate here.

2022-05-18 13:31 UTC, 0x009922 commented on packages/ui/src/components/Menu/api.ts
> +}
Additional short documentation for methods & props would be appreciated.

2022-05-18 13:31 UTC, 0x009922 commented on packages/ui/src/components/Menu/SMenuItem.vue
> +  }>(),
`index` feels confusing. Why not `value`, like native `<option>` has?

2022-05-18 13:31 UTC, 0x009922 commented on packages/ui/src/components/Menu/SMenuItem.vue
> +}
I think `SMenuItem` shouldn't be used out of `SMenu`.

2022-05-18 13:31 UTC, 0x009922 commented on packages/ui/src/components/Menu/SSubmenu.vue
> +}
Same as for `SMenuItem` - it shouldn't be used out of `SMenu`.

2022-05-18 13:31 UTC, 0x009922 commented on packages/ui/src/components/Menu/SMenuItem.vue
> +  })
This mechanism seems fragile - what if there are multiple menu items with the same index? Also, what if `index` is reactive?

2022-05-18 13:31 UTC, 0x009922 commented on packages/ui/src/components/Menu/SMenuItemBody.vue
> +  }>(),
Personally I would like to rename `minified` to `collapse`

2022-05-18 13:31 UTC, 0x009922 commented on packages/ui/src/components/Menu/SSubmenu.vue
> +})
`hasActiveItem` and `isMenuCollapsed` could be initially `true` (if `menuApi` exists). Thus, these watchers should be `immediate: true`.

2022-05-18 13:31 UTC, 0x009922 commented on packages/ui/src/components/Menu/SSubmenu.vue
> +})
Also, they could be rewritten with `whenever`:

```ts
import { and, not } from '@vueuse/shared'

whenever(and(not(isMenuCollapsed), hasActiveItem), () => toggle(true), { immediate: true })

whenever(isMenuCollapsed, () => toggle(false), { immediate: true })
```

2022-05-19 12:01 UTC, 0x009922 commented on packages/ui/src/components/Menu/SMenuItem.vue
> +  })
My idea:

```ts
import { InjectionKey, Ref, computed, inject, onScopeDispose, provide, ref, shallowReactive } from 'vue'

interface Api {
  register: (value: Ref<string>) => { isActive: Ref<boolean>; select: () => void }
}

const API_KEY: InjectionKey<Api> = Symbol('something')

// in parent

function setupParent(props: { modelValue: string }) {
  const activeValue = computed({
    get: () => props.modelValue,
    set: (v) => {
      // updating model value
    },
  })

  const registered = shallowReactive<Set<{ value: Ref<string> }>>(new Set())

  provide(API_KEY, {
    register: (value) => {
      const obj = { value }
      registered.add(obj)

      onScopeDispose(() => registered.delete(obj))

      return {
        isActive: computed(() => activeValue.value === value.value),
        select: () => {
          activeValue.value = value.value
        },
      }
    },
  })
}

// in child

function setupChild(props: { value: string }) {
  const value = computed(() => props.value)

  const { register } = inject(API_KEY)!

  const { isActive, select } = register(value)

  return { isActive, select }
}

```

2022-05-20 07:17 UTC, 0x009922 commented on packages/ui/src/components/Menu/SMenuItem.vue
>    isInSubmenu.value = true
No need for `isInSubmenu` to be a `Ref<boolean>`. It can be just a `boolean`.

2022-05-20 07:17 UTC, 0x009922 commented on packages/ui/src/components/Menu/SSubmenu.vue
> +let hasActiveItem = computed(() => [...includedItems].map((x) => x.value).includes(menuApi.active.value))
I'd refactor it in a more efficient & clear (subjectively) way:

```ts
const value = menuApi.active.value
for (const item of includedItems) {
  if (item.value === value) return true
}
return false
```

2022-05-20 07:17 UTC, 0x009922 commented on packages/ui/src/components/Menu/SMenuItem.vue
> +    submenuApi.unregister(ref(props.index))
It is not gonna work... Created ref is not updated when `props.index` is updated. You should pass `computed(() => props.index)`.

2022-05-20 07:17 UTC, 0x009922 commented on packages/ui/src/components/Menu/SMenuItem.vue
>    if (menuApi) {
About `event: HTMLElement`:

- AFAIK actual typing is `Event` or `ClickEvent`
- `event` is unused anyway. And I seems to me unclear why parent might need to get `Element` from the child on click.

2022-05-23 08:42 UTC, 0x009922 requested changes

2022-05-23 08:42 UTC, 0x009922 commented on packages/ui/src/components/NavigationMenu/SNavigationMenu.vue
> +provide(MENU_API_KEY, api)
Actually it is a good practice to `provide` APIs wrapped into `readonly()`, so it will prevent some hard-debuggable situations from happening.

2022-05-23 08:42 UTC, 0x009922 commented on packages/ui/src/components/NavigationMenu/SNavigationMenu.vue
> +    collapsed?: boolean
Doccoments would be appreciated.

2022-05-23 08:42 UTC, 0x009922 commented on packages/ui/src/components/NavigationMenu/SNavigationMenuItem.vue
> +  }
`useMenuApi()` uses `forceInject()`, so `menuApi` always exists. `if` check is unnecessary.

2022-05-23 08:42 UTC, 0x009922 commented on packages/ui/src/components/NavigationMenu/SNavigationMenuItem.vue
> +  isInSubmenu.value = true
And again, `isInSubmenu` don't need to be reactive. It's value set during `setup()` and never changes.

2022-05-23 08:42 UTC, 0x009922 commented on packages/ui/src/components/NavigationMenu/SNavigationMenuItem.vue
> +  }>(),
I'd insint to use `value` instead of `index` )
And doccomments would be appreciated.

2022-05-23 08:42 UTC, 0x009922 commented on packages/ui/src/components/NavigationMenu/SNavigationMenutemBody.vue
> +<script lang="ts">
Please fix file name - it is SNavigationMenu*tem*Body.

2022-05-23 08:42 UTC, 0x009922 commented on packages/ui/src/components/NavigationMenu/api.ts
> +}
I think its better to move `unregister` logic inside of `register` (1) without need to pass the same `Ref` twice and (2) preventing caller from forgetting to unregister on scope dispose.

2022-05-23 08:45 UTC, 0x009922 commented on packages/ui/src/components/NavigationMenu/api.ts
> +}
Also it would be nice to mention that `register` should be called during `setup` and that it will be unregistered automatically on scope dispose.

2022-05-25 09:16 UTC, 0x009922 approved these changes
LGTM

2022-05-31 13:03 UTC, alexnatalia approved these changes

2022-05-31 13:10 UTC, merged